# Generated by Django 5.0.6 on 2024-06-27 09:50

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceimage',
            name='image',
            field=models.ImageField(upload_to=users.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='idcardimage',
            name='image',
            field=models.ImageField(upload_to=users.models.user_directory_path),
        ),
    ]
